OpenXR Specification 1.0.17 (2021-06-08)
This release includes a variety of new vendor extensions, as well as
some clean-up changes to the API registry and specification, mostly
related to valid/available return codes. An update to an earlier vendor
extension is also included.

-   Registry
    -   Add XR_MSFT_scene_understanding vendor extension. (internal MR
        2032)
    -   Add XR_MSFT_scene_understanding_serialization vendor extension.
        (internal MR 2032)
    -   Add XR_MSFT_composition_layer_reprojection vendor extension.
        (internal MR 2033)
    -   Add XR_OCULUS_audio_device_guid vendor extension. (internal MR
        2053)
    -   Add version 3 of XR_FB_swapchain_update_state vendor extension,
        which splits platform and graphics API specific structs into
        separate extensions. (internal MR 2059)
    -   Apply formatting to registry XML by selectively committing
        changes made by https://github.com/rpavlik/PrettyRegistryXml.
        (internal MR 2070, OpenXR-SDK-Source/#256)
    -   Enforce that all xrCreate functions must be able to return
        XR_ERROR_LIMIT_REACHED and XR_ERROR_OUT_OF_MEMORY, and adjust
        lists of error codes accordingly. (internal MR 2064)
    -   Fix a usage of > without escaping as an XML entity. (internal MR
        2064)
    -   Fix all cases of a success code (most often
        XR_SESSION_LOSS_PENDING) appearing in the errorcodes attribute
        of a command. (internal MR 2064, internal issue 1566)
    -   Improve comments for several enum values. (internal MR 1982)
    -   Perform some script clean-up and refactoring, including
        selective type annotation and moving the Conventions abstract
        base class to spec_tools. (internal MR 2064)
    -   Sort return codes, with some general, popular codes made to be
        early. Script sort_codes.py can be used to maintain this, though
        it mangles other XML formatting, so use it with care.
        https://github.com/rpavlik/PrettyRegistryXml can format, and
        eventually sort return codes (currently sort order does not
        match). (internal MR 2064, OpenXR-SDK-Source/#256)
-   Specification
    -   Clarify that values for a given query to
        xrEnumerateBoundSourcesForAction may only change at
        xrSyncActions. (internal MR 2026, internal issue 1540,
        OpenXR-Docs/#82)
    -   Document new XR_MSFT_scene_understanding extension. (internal MR
        2032)
    -   Document new XR_MSFT_scene_understanding_serialization
        extension. (internal MR 2032)
    -   Document new XR_MSFT_composition_layer_reprojection vendor
        extension. (internal MR 2033)
    -   Document new XR_OCULUS_audio_device_guid extension. (internal MR
        2053)
    -   Document version 2 of XR_FB_swapchain_update_state which
        provides a mechanism to query state. (internal MR 2048)
    -   Document version 3 of XR_FB_swapchain_update_state which splits
        platform and graphics API specific structs into separate
        extensions. (internal MR 2059)
    -   Make explicit the recommended use of preferred swapchain texture
        formats. (internal MR 2061)
    -   Reserve extension numbers 167-176 for Facebook use. (internal MR
        2060)
    -   Use flag descriptions generated from XML comments for
        XrSpaceVelocityFlagBits, XrSwapchainUsageFlagBits, and
        XrCompositionLayerFlagBits in the specification. (internal MR
        1982)

diff --git a/specification/checkMarkup b/specification/checkMarkup
--- a/specification/checkMarkup
+++ b/specification/checkMarkup
@@ -21,11 +21,11 @@
 #
 # Usage: checkMarkup
 
-FAILED=
+set -e
 
 list_sources() {
     (
-        cd $(dirname $0)
+        cd "$(dirname $0)"
         find sources/chapters -name "*.adoc" | grep -v "extensions/meta/"
     )
 }
@@ -42,7 +42,7 @@ grep_sources() {
     shift
     if ${GREPCMD:-egrep} -n "$@" ${SOURCES}; then
         echo ""
-        echo "*** Error: Above lines matched grep with  $@"
+        echo "*** Error: Above lines matched grep with  $*"
         echo "*** $DESC"
         echo ""
         echo ""
@@ -107,8 +107,8 @@ check_markups() {
     shift
     pattern="$1"
     shift
-    for markup_type in $@; do
-        check_${markup_type}_markup $letter "$category" "$expected" "$pattern"
+    for markup_type in "$@"; do
+        "check_${markup_type}_markup" "$letter" "$category" "$expected" "$pattern"
     done
 }
 
@@ -116,7 +116,9 @@ check_markups() {
 # Actual Checks
 ###
 (
-cd $(dirname $0)
+export FAILED=
+
+cd "$(dirname $0)"
 # "f" markup: check function naming convention
 check_markups f "function names" "start with xr" "X[rR]" link name text
 
@@ -212,6 +214,7 @@ grep_sources \
     "We have decided to consistently use 'projection' rather than 'multiprojection'" \
     "\b[Mm]ulti(-?)[Pp]rojection"
 
+# shellcheck disable=SC2016
 grep_sources \
     "Per the style guide, the text NULL should be marked up as code:NULL" \
     '`NULL`'
@@ -301,9 +304,10 @@ grep_sources \
 #    "test" \
 #    "basetype:"
 
-)
-
-if [ "$FAILED" ]; then
+if [ "$FAILED" != "" ]; then
     echo "Failures detected"
     exit 1
 fi
+
+)
+
